# Generated by Django 4.1.5 on 2023-01-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationcomment',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
