# Generated by Django 4.1.5 on 2023-01-18 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_userrating_organizationrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationrating',
            old_name='rating',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='userrating',
            old_name='rating',
            new_name='value',
        ),
    ]
