# Generated by Django 4.1.5 on 2023-01-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
