# Generated by Django 4.1.5 on 2023-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='activation_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
