# Generated by Django 4.1.5 on 2023-01-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delivery_activation_code_delivery_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='is_active',
        ),
    ]
